package sistemas.operativos.proyecto1.gui;

import sistemas.operativos.proyecto1.Simulator;
import sistemas.operativos.proyecto1.Stats;

/**
 *
 * @author sebas
 */
public class ConfigView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfigView.class.getName());
    private final Simulator sim;
    private final Stats stats;

    /**
     * Creates new form ConfigView
     * @param sim
     * @param stats
     */
    public ConfigView(Simulator sim, Stats stats) {
        initComponents();
        this.sim = sim;
        this.stats = stats;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cyclesDurationField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cyclesAmountField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cyclesQuantumField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        cyclesDurationField.setBackground(new java.awt.Color(24, 24, 24));
        cyclesDurationField.setForeground(new java.awt.Color(255, 255, 255));
        cyclesDurationField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cyclesDurationField.setText("100");
        cyclesDurationField.setBorder(null);
        cyclesDurationField.setCaretColor(new java.awt.Color(255, 255, 255));
        cyclesDurationField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cyclesDurationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyclesDurationFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Duración de ciclos:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Cantidad de ciclos:");
        jLabel6.setToolTipText("");

        cyclesAmountField.setBackground(new java.awt.Color(24, 24, 24));
        cyclesAmountField.setForeground(new java.awt.Color(255, 255, 255));
        cyclesAmountField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cyclesAmountField.setText("200");
        cyclesAmountField.setBorder(null);
        cyclesAmountField.setCaretColor(new java.awt.Color(255, 255, 255));
        cyclesAmountField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cyclesAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyclesAmountFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Quantum en ciclos:");
        jLabel7.setToolTipText("");

        cyclesQuantumField.setBackground(new java.awt.Color(24, 24, 24));
        cyclesQuantumField.setForeground(new java.awt.Color(255, 255, 255));
        cyclesQuantumField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cyclesQuantumField.setText("200");
        cyclesQuantumField.setBorder(null);
        cyclesQuantumField.setCaretColor(new java.awt.Color(255, 255, 255));
        cyclesQuantumField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cyclesQuantumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyclesQuantumFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cyclesQuantumField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(cyclesAmountField)
                    .addComponent(cyclesDurationField))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cyclesDurationField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cyclesAmountField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cyclesQuantumField))
                .addContainerGap())
        );

        cancelButton.setBackground(new java.awt.Color(85, 85, 85));
        cancelButton.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setFocusable(false);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelButtonMousePressed(evt);
            }
        });

        confirmButton.setBackground(new java.awt.Color(85, 85, 85));
        confirmButton.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirmar");
        confirmButton.setFocusable(false);
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmButtonMousePressed(evt);
            }
        });
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmButton))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmButton))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cyclesDurationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyclesDurationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cyclesDurationFieldActionPerformed

    private void cyclesAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyclesAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cyclesAmountFieldActionPerformed

    private void cyclesQuantumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyclesQuantumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cyclesQuantumFieldActionPerformed

    private void cancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMousePressed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMousePressed

    private void confirmButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMousePressed
        this.updateConfig();
        
        this.setVisible(false);
    }//GEN-LAST:event_confirmButtonMousePressed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed

    public void updateConfig() {
        String amount = this.cyclesAmountField.getText();
        String duration = this.cyclesDurationField.getText();
        String quantum = this.cyclesQuantumField.getText();
        
        try {
            int amountParsed = Integer.parseInt(amount);
            this.sim.setCyclesAmount(amountParsed);
        } catch (NumberFormatException e) {
        }
        
        try {
            long durationParsed = Long.parseLong(duration);
            this.sim.setCyclesDuration(durationParsed);
        } catch (NumberFormatException e) {
        }
        
        try {
            int quantumParsed = Integer.parseInt(quantum);
            this.sim.setCyclesQuantum(quantumParsed);
        } catch (NumberFormatException e) {
        }
    }
    
    public void loadConfig() {
        this.cyclesAmountField.setText(String.valueOf(this.sim.getCyclesAmount()));
        this.cyclesDurationField.setText(String.valueOf(this.sim.getCyclesDuration()));
        this.cyclesQuantumField.setText(String.valueOf(this.sim.getCyclesQuantum()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField cyclesAmountField;
    private javax.swing.JTextField cyclesDurationField;
    private javax.swing.JTextField cyclesQuantumField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
