package sistemas.operativos.proyecto1.gui;

import sistemas.operativos.proyecto1.Simulator;
import sistemas.operativos.proyecto1.Stats;
import sistemas.operativos.proyecto1.process.ProcessType;

/**
 *
 * @author sebas
 */
public class CreateView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateView.class.getName());
    private final Simulator sim;
    private final Stats stats;
    private final MainView parent;

    /**
     * Creates new form CreateView
     * @param sim
     * @param stats
     * @param parent
     */
    public CreateView(Simulator sim, Stats stats, MainView parent) {
        initComponents();
        this.sim = sim;
        this.stats = stats;
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        arrivalField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        instructionsField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        exceptionField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        satisfyField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        priorityField = new javax.swing.JTextField();
        planPolicySelector = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        nameField.setBackground(new java.awt.Color(24, 24, 24));
        nameField.setForeground(new java.awt.Color(255, 255, 255));
        nameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameField.setText("Proceso");
        nameField.setBorder(null);
        nameField.setCaretColor(new java.awt.Color(255, 255, 255));
        nameField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nombre:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Tiempo de llegada:");
        jLabel6.setToolTipText("");

        arrivalField.setBackground(new java.awt.Color(24, 24, 24));
        arrivalField.setForeground(new java.awt.Color(255, 255, 255));
        arrivalField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        arrivalField.setText("0");
        arrivalField.setBorder(null);
        arrivalField.setCaretColor(new java.awt.Color(255, 255, 255));
        arrivalField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        arrivalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Instrucciones:");
        jLabel7.setToolTipText("");

        instructionsField.setBackground(new java.awt.Color(24, 24, 24));
        instructionsField.setForeground(new java.awt.Color(255, 255, 255));
        instructionsField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        instructionsField.setText("30");
        instructionsField.setBorder(null);
        instructionsField.setCaretColor(new java.awt.Color(255, 255, 255));
        instructionsField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        instructionsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Tipo de proceso:");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Ciclos para excepción:");
        jLabel9.setToolTipText("");

        exceptionField.setBackground(new java.awt.Color(24, 24, 24));
        exceptionField.setForeground(new java.awt.Color(255, 255, 255));
        exceptionField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        exceptionField.setText("1");
        exceptionField.setBorder(null);
        exceptionField.setCaretColor(new java.awt.Color(255, 255, 255));
        exceptionField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        exceptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exceptionFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Ciclos para satisfacción:");
        jLabel10.setToolTipText("");

        satisfyField.setBackground(new java.awt.Color(24, 24, 24));
        satisfyField.setForeground(new java.awt.Color(255, 255, 255));
        satisfyField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        satisfyField.setText("1");
        satisfyField.setBorder(null);
        satisfyField.setCaretColor(new java.awt.Color(255, 255, 255));
        satisfyField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        satisfyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisfyFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Prioridad:");
        jLabel11.setToolTipText("");

        priorityField.setBackground(new java.awt.Color(24, 24, 24));
        priorityField.setForeground(new java.awt.Color(255, 255, 255));
        priorityField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        priorityField.setText("1");
        priorityField.setBorder(null);
        priorityField.setCaretColor(new java.awt.Color(255, 255, 255));
        priorityField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        priorityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityFieldActionPerformed(evt);
            }
        });

        planPolicySelector.setBackground(new java.awt.Color(85, 85, 85));
        planPolicySelector.setForeground(new java.awt.Color(255, 255, 255));
        planPolicySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU_BOUND", "IO_BOUND", " " }));
        planPolicySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planPolicySelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arrivalField, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exceptionField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(satisfyField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priorityField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(planPolicySelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instructionsField)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(arrivalField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(instructionsField))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(planPolicySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(exceptionField))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(satisfyField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(priorityField))
                .addContainerGap())
        );

        cancelButton.setBackground(new java.awt.Color(85, 85, 85));
        cancelButton.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setFocusable(false);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelButtonMousePressed(evt);
            }
        });

        confirmButton.setBackground(new java.awt.Color(85, 85, 85));
        confirmButton.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Crear");
        confirmButton.setFocusable(false);
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmButtonMousePressed(evt);
            }
        });
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmButton))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(confirmButton))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void arrivalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalFieldActionPerformed

    private void instructionsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructionsFieldActionPerformed

    private void cancelButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMousePressed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMousePressed

    private void confirmButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMousePressed
        this.createProcess();
    }//GEN-LAST:event_confirmButtonMousePressed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void exceptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exceptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exceptionFieldActionPerformed

    private void satisfyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisfyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satisfyFieldActionPerformed

    private void priorityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priorityFieldActionPerformed

    private void planPolicySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planPolicySelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planPolicySelectorActionPerformed

    public void createProcess() {
        String name = this.nameField.getText();
        String arrival = this.arrivalField.getText();
        String instructions = this.instructionsField.getText();
        String type = (String) this.planPolicySelector.getSelectedItem();
        String exception = this.exceptionField.getText();
        String satisfy = this.satisfyField.getText();
        String priority = this.priorityField.getText();
        
        ProcessType typeParsed = ProcessType.CPU_BOUND;
        
        int arrivalParsed = 0;
        int instructionsParsed = 1;
        int exceptionParsed = 1;
        int satisfyParsed = 1;
        int priorityParsed = 1;
        
        boolean validate = true;
        
        if(type != null) {
            if(type.equalsIgnoreCase(ProcessType.CPU_BOUND.name())) {
                typeParsed = ProcessType.CPU_BOUND;
            } else if(type.equalsIgnoreCase(ProcessType.IO_BOUND.name())) {
                typeParsed = ProcessType.IO_BOUND;
            } else {
                validate = false;
            }
        }
        
        try {
            arrivalParsed = Integer.parseInt(arrival);
            if(arrivalParsed < 0) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            validate = false;
        }
        try {
            instructionsParsed = Integer.parseInt(instructions);
            if(instructionsParsed < 1) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            validate = false;
        }
        try {
            exceptionParsed = Integer.parseInt(exception);
            if(exceptionParsed < 1) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            validate = false;
        }
        try {
            satisfyParsed = Integer.parseInt(satisfy);
            if(satisfyParsed < 1) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            validate = false;
        }
        try {
            priorityParsed = Integer.parseInt(priority);
            if(priorityParsed < 1) throw new NumberFormatException();
        } catch (NumberFormatException e) {
            validate = false;
        }
        
        if(
            (name != null) &&
            (type != null && (type.equalsIgnoreCase(ProcessType.CPU_BOUND.name()) || type.equalsIgnoreCase(ProcessType.IO_BOUND.name()))) &&
            validate
            ) {
            this.sim.createProcess(name, arrivalParsed, instructionsParsed, typeParsed, exceptionParsed, satisfyParsed, priorityParsed);
            
            this.parent.forceUpdateFields();
            
            this.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField exceptionField;
    private javax.swing.JTextField instructionsField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox<String> planPolicySelector;
    private javax.swing.JTextField priorityField;
    private javax.swing.JTextField satisfyField;
    // End of variables declaration//GEN-END:variables
}
