/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemas.operativos.proyecto1.gui;

import sistemas.operativos.proyecto1.Simulator;
import sistemas.operativos.proyecto1.Stats;

/**
 *
 * @author sebas
 */
public class MainView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());
    private final Simulator sim;
    private final Stats stats;

    /**
     * Creates new form MainView
     * @param sim
     * @param stats
     */
    public MainView(Simulator sim, Stats stats) {
        initComponents();
        this.sim = sim;
        this.stats = stats;
        
        updateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReadyList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BlockedList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        currentProcessField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        completedProcessesField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        avgWaitField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        avgRespField = new javax.swing.JTextField();
        avgTurnField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        throughputField = new javax.swing.JTextField();
        cpuUsageField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fairnessField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        ReadyList.setBackground(new java.awt.Color(34, 34, 34));
        ReadyList.setBorder(null);
        ReadyList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ReadyList);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Cola \"LISTO\"");
        jLabel1.setToolTipText("");

        BlockedList.setBackground(new java.awt.Color(34, 34, 34));
        BlockedList.setBorder(null);
        BlockedList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(BlockedList);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Cola \"BLOQUEADO\"");
        jLabel2.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Proceso Actual:");
        jLabel4.setToolTipText("");

        currentProcessField.setBackground(new java.awt.Color(24, 24, 24));
        currentProcessField.setForeground(new java.awt.Color(255, 255, 255));
        currentProcessField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentProcessField.setText("Ninguno");
        currentProcessField.setBorder(null);
        currentProcessField.setCaretColor(new java.awt.Color(255, 255, 255));
        currentProcessField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        currentProcessField.setEnabled(false);
        currentProcessField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentProcessFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentProcessField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentProcessField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(34, 34, 34));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Procesos Completados:");
        jLabel5.setToolTipText("");

        completedProcessesField.setBackground(new java.awt.Color(24, 24, 24));
        completedProcessesField.setForeground(new java.awt.Color(255, 255, 255));
        completedProcessesField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        completedProcessesField.setText("0 de 0");
        completedProcessesField.setBorder(null);
        completedProcessesField.setCaretColor(new java.awt.Color(255, 255, 255));
        completedProcessesField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        completedProcessesField.setEnabled(false);
        completedProcessesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedProcessesFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Promedio WAIT:");
        jLabel6.setToolTipText("");

        avgWaitField.setBackground(new java.awt.Color(24, 24, 24));
        avgWaitField.setForeground(new java.awt.Color(255, 255, 255));
        avgWaitField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        avgWaitField.setText("0.0");
        avgWaitField.setBorder(null);
        avgWaitField.setCaretColor(new java.awt.Color(255, 255, 255));
        avgWaitField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        avgWaitField.setEnabled(false);
        avgWaitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgWaitFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Promedio RESP:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Promedio TURN:");
        jLabel8.setToolTipText("");

        avgRespField.setBackground(new java.awt.Color(24, 24, 24));
        avgRespField.setForeground(new java.awt.Color(255, 255, 255));
        avgRespField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        avgRespField.setText("0.0");
        avgRespField.setBorder(null);
        avgRespField.setCaretColor(new java.awt.Color(255, 255, 255));
        avgRespField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        avgRespField.setEnabled(false);
        avgRespField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgRespFieldActionPerformed(evt);
            }
        });

        avgTurnField.setBackground(new java.awt.Color(24, 24, 24));
        avgTurnField.setForeground(new java.awt.Color(255, 255, 255));
        avgTurnField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        avgTurnField.setText("0.0");
        avgTurnField.setBorder(null);
        avgTurnField.setCaretColor(new java.awt.Color(255, 255, 255));
        avgTurnField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        avgTurnField.setEnabled(false);
        avgTurnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgTurnFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Utilización de CPU:");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Throughput:");
        jLabel10.setToolTipText("");

        throughputField.setBackground(new java.awt.Color(24, 24, 24));
        throughputField.setForeground(new java.awt.Color(255, 255, 255));
        throughputField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        throughputField.setText("0");
        throughputField.setBorder(null);
        throughputField.setCaretColor(new java.awt.Color(255, 255, 255));
        throughputField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        throughputField.setEnabled(false);
        throughputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throughputFieldActionPerformed(evt);
            }
        });

        cpuUsageField.setBackground(new java.awt.Color(24, 24, 24));
        cpuUsageField.setForeground(new java.awt.Color(255, 255, 255));
        cpuUsageField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cpuUsageField.setText("0%");
        cpuUsageField.setBorder(null);
        cpuUsageField.setCaretColor(new java.awt.Color(255, 255, 255));
        cpuUsageField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cpuUsageField.setEnabled(false);
        cpuUsageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuUsageFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Fairness:");
        jLabel11.setToolTipText("");

        fairnessField.setBackground(new java.awt.Color(24, 24, 24));
        fairnessField.setForeground(new java.awt.Color(255, 255, 255));
        fairnessField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fairnessField.setText("0");
        fairnessField.setBorder(null);
        fairnessField.setCaretColor(new java.awt.Color(255, 255, 255));
        fairnessField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        fairnessField.setEnabled(false);
        fairnessField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fairnessFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fairnessField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(completedProcessesField, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avgWaitField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(avgTurnField))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(avgRespField))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuUsageField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(throughputField)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(completedProcessesField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(avgWaitField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(avgRespField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(avgTurnField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cpuUsageField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(throughputField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fairnessField))
                .addGap(10, 10, 10))
        );

        jPanel4.setBackground(new java.awt.Color(34, 34, 34));

        startButton.setBackground(new java.awt.Color(85, 85, 85));
        startButton.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Iniciar");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startButtonMousePressed(evt);
            }
        });
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(startButton)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentProcessFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentProcessFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentProcessFieldActionPerformed

    private void completedProcessesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedProcessesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completedProcessesFieldActionPerformed

    private void avgWaitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgWaitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgWaitFieldActionPerformed

    private void avgRespFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgRespFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgRespFieldActionPerformed

    private void avgTurnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgTurnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgTurnFieldActionPerformed

    private void throughputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throughputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_throughputFieldActionPerformed

    private void cpuUsageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuUsageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpuUsageFieldActionPerformed

    private void fairnessFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fairnessFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fairnessFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed

    private void startButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMousePressed
        Thread starter = new Thread(() -> {
            sim.startSimulation();
        }, "Starter-Thread");
        
        starter.start();
        
        this.startButton.setEnabled(false);
    }//GEN-LAST:event_startButtonMousePressed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new MainView().setVisible(true));
    }
    
    public void updateFields() {
        Thread updater = new Thread(() -> {
            while(true) {
                try {
                    Thread.sleep(500);

                    String newCompletedProcessesField = String.valueOf(this.stats.completedProcesses) + " de " + String.valueOf(this.stats.totalProcesses);
                    String newAvgWaitField = Double.isNaN(this.stats.avgWait) ? "0.00" : String.format("%.2f", this.stats.avgWait);
                    String newAvgRespField = Double.isNaN(this.stats.avgResp) ? "0.00" : String.format("%.2f", this.stats.avgResp);
                    String newAvgTurnField = Double.isNaN(this.stats.avgTurn) ? "0.00" : String.format("%.2f", this.stats.avgTurn);
                    String newCpuUsageField = String.format("%.1f", this.stats.util) + "%";
                    String newThroughputField = Double.isNaN(this.stats.throughput) ? "0.0000" : String.format("%.4f", this.stats.throughput);
                    String newFairnessField = Double.isNaN(this.stats.fairness) ? "0.000" : String.format("%.3f", this.stats.fairness);
                    
                    String newCurrentField = this.stats.isCurrentProcessAvailable() ? this.stats.currentProcess.name() : "Ninguno";
                    String[] newReadyList = this.stats.getReadyQueueList();
                    String[] newIoList = this.stats.getIoQueueList();

                    this.completedProcessesField.setText(newCompletedProcessesField);
                    this.avgWaitField.setText(newAvgWaitField);
                    this.avgRespField.setText(newAvgRespField);
                    this.avgTurnField.setText(newAvgTurnField);
                    this.cpuUsageField.setText(newCpuUsageField);
                    this.throughputField.setText(newThroughputField);
                    this.fairnessField.setText(newFairnessField);
                    
                    this.currentProcessField.setText(newCurrentField);
                    this.ReadyList.setListData(newReadyList);
                    this.BlockedList.setListData(newIoList);
                } catch (InterruptedException e) {
                     Thread.currentThread().interrupt();
                }
            }
        }, "External-Updater");

       
        updater.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> BlockedList;
    private javax.swing.JList<String> ReadyList;
    private javax.swing.JTextField avgRespField;
    private javax.swing.JTextField avgTurnField;
    private javax.swing.JTextField avgWaitField;
    private javax.swing.JTextField completedProcessesField;
    private javax.swing.JTextField cpuUsageField;
    private javax.swing.JTextField currentProcessField;
    private javax.swing.JTextField fairnessField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField throughputField;
    // End of variables declaration//GEN-END:variables
}
