package sistemas.operativos.proyecto1.gui;

import javax.swing.JFrame;
import sistemas.operativos.proyecto1.Simulator;
import sistemas.operativos.proyecto1.Stats;
import sistemas.operativos.proyecto1.PlanPolicy;

/**
 *
 * @author sebas
 */
public class MainView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());
    private final Simulator sim;
    private final Stats stats;
    private Thread starter;
    private boolean running;
    private JFrame configView;
    private JFrame createView;

    /**
     * Creates new form MainView
     * @param sim
     * @param stats
     */
    public MainView(Simulator sim, Stats stats) {
        initComponents();
        this.sim = sim;
        this.stats = stats;
        
        this.configView = new ConfigView(sim, stats);
        this.createView = new CreateView(sim, stats, this);
        
        this.running = true;
        this.starter = new Thread(() -> {
            stats.addLog("Simulación iniciada.");
            
            this.running = true;
            sim.startSimulation();
            
            this.startButton.setEnabled(true);
            this.pauseButton.setEnabled(false);
            this.configButton.setEnabled(true);
            this.createButton.setEnabled(true);
            this.planPolicySelector.setEnabled(true);
            this.configView.setVisible(false);
            this.createView.setVisible(false);
            this.running = false;
        }, "Starter-Thread");
        
        forceUpdateFields();
        updateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReadyList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BlockedList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        completedProcessesField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        avgWaitField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        avgRespField = new javax.swing.JTextField();
        avgTurnField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        throughputField = new javax.swing.JTextField();
        cpuUsageField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fairnessField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        currentProcessField = new javax.swing.JTextField();
        cycleField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        currentProcessIDField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        currentProcessNameField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        currentProcessInstructionsField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        currentProcessPriorityField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        currentProcessPCField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        currentProcessMARField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        planPolicySelector = new javax.swing.JComboBox<>();
        pauseButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        LogsList = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FinishedList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        configButton = new javax.swing.JMenu();
        createButton = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        ReadyList.setBackground(new java.awt.Color(34, 34, 34));
        ReadyList.setBorder(null);
        ReadyList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ReadyList);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Cola \"LISTO\"");
        jLabel1.setToolTipText("");

        BlockedList.setBackground(new java.awt.Color(34, 34, 34));
        BlockedList.setBorder(null);
        BlockedList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(BlockedList);

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Cola \"BLOQUEADO\"");
        jLabel2.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(34, 34, 34));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Procesos Completados:");
        jLabel5.setToolTipText("");

        completedProcessesField.setBackground(new java.awt.Color(24, 24, 24));
        completedProcessesField.setForeground(new java.awt.Color(255, 255, 255));
        completedProcessesField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        completedProcessesField.setText("0 de 0");
        completedProcessesField.setBorder(null);
        completedProcessesField.setCaretColor(new java.awt.Color(255, 255, 255));
        completedProcessesField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        completedProcessesField.setEnabled(false);
        completedProcessesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedProcessesFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Promedio WAIT:");
        jLabel6.setToolTipText("");

        avgWaitField.setBackground(new java.awt.Color(24, 24, 24));
        avgWaitField.setForeground(new java.awt.Color(255, 255, 255));
        avgWaitField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        avgWaitField.setText("0.0");
        avgWaitField.setBorder(null);
        avgWaitField.setCaretColor(new java.awt.Color(255, 255, 255));
        avgWaitField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        avgWaitField.setEnabled(false);
        avgWaitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgWaitFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Promedio RESP:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Promedio TURN:");
        jLabel8.setToolTipText("");

        avgRespField.setBackground(new java.awt.Color(24, 24, 24));
        avgRespField.setForeground(new java.awt.Color(255, 255, 255));
        avgRespField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        avgRespField.setText("0.0");
        avgRespField.setBorder(null);
        avgRespField.setCaretColor(new java.awt.Color(255, 255, 255));
        avgRespField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        avgRespField.setEnabled(false);
        avgRespField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgRespFieldActionPerformed(evt);
            }
        });

        avgTurnField.setBackground(new java.awt.Color(24, 24, 24));
        avgTurnField.setForeground(new java.awt.Color(255, 255, 255));
        avgTurnField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        avgTurnField.setText("0.0");
        avgTurnField.setBorder(null);
        avgTurnField.setCaretColor(new java.awt.Color(255, 255, 255));
        avgTurnField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        avgTurnField.setEnabled(false);
        avgTurnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgTurnFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Utilización de CPU:");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Throughput:");
        jLabel10.setToolTipText("");

        throughputField.setBackground(new java.awt.Color(24, 24, 24));
        throughputField.setForeground(new java.awt.Color(255, 255, 255));
        throughputField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        throughputField.setText("0");
        throughputField.setBorder(null);
        throughputField.setCaretColor(new java.awt.Color(255, 255, 255));
        throughputField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        throughputField.setEnabled(false);
        throughputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throughputFieldActionPerformed(evt);
            }
        });

        cpuUsageField.setBackground(new java.awt.Color(24, 24, 24));
        cpuUsageField.setForeground(new java.awt.Color(255, 255, 255));
        cpuUsageField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cpuUsageField.setText("0%");
        cpuUsageField.setBorder(null);
        cpuUsageField.setCaretColor(new java.awt.Color(255, 255, 255));
        cpuUsageField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cpuUsageField.setEnabled(false);
        cpuUsageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuUsageFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Fairness:");
        jLabel11.setToolTipText("");

        fairnessField.setBackground(new java.awt.Color(24, 24, 24));
        fairnessField.setForeground(new java.awt.Color(255, 255, 255));
        fairnessField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fairnessField.setText("0");
        fairnessField.setBorder(null);
        fairnessField.setCaretColor(new java.awt.Color(255, 255, 255));
        fairnessField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        fairnessField.setEnabled(false);
        fairnessField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fairnessFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fairnessField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(completedProcessesField, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avgWaitField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(avgTurnField))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(avgRespField))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpuUsageField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(throughputField)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(completedProcessesField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(avgWaitField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(avgRespField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(avgTurnField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cpuUsageField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(throughputField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fairnessField))
                .addGap(10, 10, 10))
        );

        jPanel4.setBackground(new java.awt.Color(34, 34, 34));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Proceso Actual:");
        jLabel4.setToolTipText("");

        currentProcessField.setBackground(new java.awt.Color(24, 24, 24));
        currentProcessField.setForeground(new java.awt.Color(255, 255, 255));
        currentProcessField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentProcessField.setText("Ninguno");
        currentProcessField.setBorder(null);
        currentProcessField.setCaretColor(new java.awt.Color(255, 255, 255));
        currentProcessField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        currentProcessField.setEnabled(false);
        currentProcessField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentProcessFieldActionPerformed(evt);
            }
        });

        cycleField.setBackground(new java.awt.Color(24, 24, 24));
        cycleField.setForeground(new java.awt.Color(255, 255, 255));
        cycleField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cycleField.setText("0");
        cycleField.setBorder(null);
        cycleField.setCaretColor(new java.awt.Color(255, 255, 255));
        cycleField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        cycleField.setEnabled(false);
        cycleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cycleFieldActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Ciclo:");
        jLabel19.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentProcessField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cycleField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cycleField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(currentProcessField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Detalles del proceso");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("ID:");
        jLabel13.setToolTipText("");

        currentProcessIDField.setBackground(new java.awt.Color(24, 24, 24));
        currentProcessIDField.setForeground(new java.awt.Color(255, 255, 255));
        currentProcessIDField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentProcessIDField.setText("Ninguno");
        currentProcessIDField.setBorder(null);
        currentProcessIDField.setCaretColor(new java.awt.Color(255, 255, 255));
        currentProcessIDField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        currentProcessIDField.setEnabled(false);
        currentProcessIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentProcessIDFieldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Nombre:");
        jLabel14.setToolTipText("");

        currentProcessNameField.setBackground(new java.awt.Color(24, 24, 24));
        currentProcessNameField.setForeground(new java.awt.Color(255, 255, 255));
        currentProcessNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentProcessNameField.setText("Ninguno");
        currentProcessNameField.setBorder(null);
        currentProcessNameField.setCaretColor(new java.awt.Color(255, 255, 255));
        currentProcessNameField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        currentProcessNameField.setEnabled(false);
        currentProcessNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentProcessNameFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Instrucciones restantes:");
        jLabel15.setToolTipText("");

        currentProcessInstructionsField.setBackground(new java.awt.Color(24, 24, 24));
        currentProcessInstructionsField.setForeground(new java.awt.Color(255, 255, 255));
        currentProcessInstructionsField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentProcessInstructionsField.setText("0 de 0");
        currentProcessInstructionsField.setBorder(null);
        currentProcessInstructionsField.setCaretColor(new java.awt.Color(255, 255, 255));
        currentProcessInstructionsField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        currentProcessInstructionsField.setEnabled(false);
        currentProcessInstructionsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentProcessInstructionsFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Nivel de prioridad:");
        jLabel16.setToolTipText("");

        currentProcessPriorityField.setBackground(new java.awt.Color(24, 24, 24));
        currentProcessPriorityField.setForeground(new java.awt.Color(255, 255, 255));
        currentProcessPriorityField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentProcessPriorityField.setText("0");
        currentProcessPriorityField.setBorder(null);
        currentProcessPriorityField.setCaretColor(new java.awt.Color(255, 255, 255));
        currentProcessPriorityField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        currentProcessPriorityField.setEnabled(false);
        currentProcessPriorityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentProcessPriorityFieldActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("PC:");
        jLabel17.setToolTipText("");

        currentProcessPCField.setBackground(new java.awt.Color(24, 24, 24));
        currentProcessPCField.setForeground(new java.awt.Color(255, 255, 255));
        currentProcessPCField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentProcessPCField.setText("0");
        currentProcessPCField.setBorder(null);
        currentProcessPCField.setCaretColor(new java.awt.Color(255, 255, 255));
        currentProcessPCField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        currentProcessPCField.setEnabled(false);
        currentProcessPCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentProcessPCFieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("MAR:");
        jLabel18.setToolTipText("");

        currentProcessMARField.setBackground(new java.awt.Color(24, 24, 24));
        currentProcessMARField.setForeground(new java.awt.Color(255, 255, 255));
        currentProcessMARField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        currentProcessMARField.setText("0");
        currentProcessMARField.setBorder(null);
        currentProcessMARField.setCaretColor(new java.awt.Color(255, 255, 255));
        currentProcessMARField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        currentProcessMARField.setEnabled(false);
        currentProcessMARField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentProcessMARFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentProcessMARField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentProcessPCField))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentProcessPriorityField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentProcessInstructionsField))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentProcessNameField))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentProcessIDField)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentProcessIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentProcessNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentProcessInstructionsField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(currentProcessPriorityField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(currentProcessPCField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(currentProcessMARField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        startButton.setBackground(new java.awt.Color(85, 85, 85));
        startButton.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        startButton.setForeground(new java.awt.Color(255, 255, 255));
        startButton.setText("Iniciar");
        startButton.setFocusable(false);
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startButtonMousePressed(evt);
            }
        });
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        planPolicySelector.setBackground(new java.awt.Color(85, 85, 85));
        planPolicySelector.setForeground(new java.awt.Color(255, 255, 255));
        planPolicySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "RR", "SPN", "SRT", "PRI", "MFQ" }));
        planPolicySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planPolicySelectorActionPerformed(evt);
            }
        });

        pauseButton.setBackground(new java.awt.Color(85, 85, 85));
        pauseButton.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        pauseButton.setForeground(new java.awt.Color(255, 255, 255));
        pauseButton.setText("Pausar");
        pauseButton.setEnabled(false);
        pauseButton.setFocusable(false);
        pauseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pauseButtonMousePressed(evt);
            }
        });
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planPolicySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(planPolicySelector, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startButton)
                        .addComponent(pauseButton)))
                .addContainerGap())
        );

        LogsList.setBackground(new java.awt.Color(24, 24, 24));
        LogsList.setBorder(null);
        LogsList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(LogsList);

        jLabel20.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Logs");
        jLabel20.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FinishedList.setBackground(new java.awt.Color(34, 34, 34));
        FinishedList.setBorder(null);
        FinishedList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(FinishedList);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Cola \"TERMINADO\"");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        configButton.setBackground(new java.awt.Color(51, 51, 51));
        configButton.setForeground(new java.awt.Color(255, 255, 255));
        configButton.setText("Configurar");
        configButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                configButtonMousePressed(evt);
            }
        });
        jMenuBar1.add(configButton);

        createButton.setBackground(new java.awt.Color(51, 51, 51));
        createButton.setForeground(new java.awt.Color(255, 255, 255));
        createButton.setText("Añadir Proceso");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createButtonMousePressed(evt);
            }
        });
        jMenuBar1.add(createButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentProcessFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentProcessFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentProcessFieldActionPerformed

    private void completedProcessesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedProcessesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completedProcessesFieldActionPerformed

    private void avgWaitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgWaitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgWaitFieldActionPerformed

    private void avgRespFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgRespFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgRespFieldActionPerformed

    private void avgTurnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgTurnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgTurnFieldActionPerformed

    private void throughputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throughputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_throughputFieldActionPerformed

    private void cpuUsageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuUsageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpuUsageFieldActionPerformed

    private void fairnessFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fairnessFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fairnessFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if(!running) {
            starter = new Thread(() -> {
                stats.addLog("Simulación iniciada.");
                
                this.running = true;
                sim.startSimulation();

                this.startButton.setEnabled(true);
                this.pauseButton.setEnabled(false);
                this.configButton.setEnabled(true);
                this.createButton.setEnabled(true);
                this.planPolicySelector.setEnabled(true);
                this.configView.setVisible(false);
                this.createView.setVisible(false);
                this.running = false;
            }, "Starter-Thread");
        }
        
        starter.start();
        
        this.startButton.setEnabled(false);
        this.pauseButton.setEnabled(true);
        this.configButton.setEnabled(false);
        this.createButton.setEnabled(false);
        this.planPolicySelector.setEnabled(false);
    }//GEN-LAST:event_startButtonActionPerformed

    private void startButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonMousePressed

    private void currentProcessIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentProcessIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentProcessIDFieldActionPerformed

    private void currentProcessNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentProcessNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentProcessNameFieldActionPerformed

    private void currentProcessInstructionsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentProcessInstructionsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentProcessInstructionsFieldActionPerformed

    private void currentProcessPriorityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentProcessPriorityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentProcessPriorityFieldActionPerformed

    private void currentProcessPCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentProcessPCFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentProcessPCFieldActionPerformed

    private void currentProcessMARFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentProcessMARFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentProcessMARFieldActionPerformed

    private void planPolicySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planPolicySelectorActionPerformed
        String selected = this.planPolicySelector.getSelectedItem().toString();
        
        PlanPolicy selection;
        
        try {
            selection = PlanPolicy.valueOf(selected);
            System.out.println("Selected: " + selected);
        } catch (Exception e) {
            selection = PlanPolicy.FCFS;
            System.out.println("Error: Defaulting to FCFS");
        }
        
        this.sim.getConfig().setPolicy(selection);
        this.stats.addLog("Algoritmo de planificación puesto como: " + selection.toString());
    }//GEN-LAST:event_planPolicySelectorActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        starter.interrupt();
        
        starter = new Thread(() -> {
            stats.addLog("Simulación iniciada.");
            
            this.running = true;
            sim.startSimulation();
            
            this.startButton.setEnabled(true);
            this.pauseButton.setEnabled(false);
            this.configButton.setEnabled(true);
            this.createButton.setEnabled(true);
            this.planPolicySelector.setEnabled(true);
            this.configView.setVisible(false);
            this.createView.setVisible(false);
            this.running = false;
        }, "Starter-Thread");
        
        this.startButton.setEnabled(true);
        this.pauseButton.setEnabled(false);
        this.configButton.setEnabled(true);
        this.createButton.setEnabled(true);
        this.planPolicySelector.setEnabled(true);
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void pauseButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pauseButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pauseButtonMousePressed

    private void configButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configButtonMousePressed
        // TODO add your handling code here:
        if(this.configButton.isEnabled()) configView.setVisible(true);
    }//GEN-LAST:event_configButtonMousePressed

    private void createButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMousePressed
        // TODO add your handling code here:
        if(this.createButton.isEnabled()) createView.setVisible(true);
    }//GEN-LAST:event_createButtonMousePressed

    private void cycleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cycleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cycleFieldActionPerformed

    public void updateFields() {
        Thread updater = new Thread(() -> {
            while(true) {
                try {
                    Thread.sleep(100);

                    String newCompletedProcessesField = String.valueOf(this.stats.completedProcesses) + " de " + String.valueOf(this.stats.totalProcesses);
                    String newAvgWaitField = Double.isNaN(this.stats.avgWait) ? "0.00" : String.format("%.2f", this.stats.avgWait);
                    String newAvgRespField = Double.isNaN(this.stats.avgResp) ? "0.00" : String.format("%.2f", this.stats.avgResp);
                    String newAvgTurnField = Double.isNaN(this.stats.avgTurn) ? "0.00" : String.format("%.2f", this.stats.avgTurn);
                    String newCpuUsageField = String.format("%.1f", this.stats.util) + "%";
                    String newThroughputField = Double.isNaN(this.stats.throughput) ? "0.0000" : String.format("%.4f", this.stats.throughput);
                    String newFairnessField = Double.isNaN(this.stats.fairness) ? "0.000" : String.format("%.3f", this.stats.fairness);
                    
                    String newCurrentField = this.stats.isCurrentProcessAvailable() ? this.stats.currentProcess.name() : "Ninguno";
                    String[] newReadyList = this.stats.getReadyQueueList();
                    String[] newIoList = this.stats.getIoQueueList();
                    String[] newfinishedList = this.stats.getFinishedQueueList();
                    
                    String newId = this.stats.isCurrentProcessAvailable() ? this.stats.currentProcess.id() : "Ninguno";
                    String newName = this.stats.isCurrentProcessAvailable() ? this.stats.currentProcess.name() : "Ninguno";
                    String newInstructions = this.stats.isCurrentProcessAvailable() ? String.valueOf(this.stats.currentProcess.remaining()) + " de " + String.valueOf(this.stats.currentProcess.instructions()) : "0 de 0";
                    String newPriority = this.stats.isCurrentProcessAvailable() ? String.valueOf(this.stats.currentProcess.priority()) : "0";
                    String newPC = this.stats.isCurrentProcessAvailable() ? String.valueOf(this.stats.currentProcess.pc()) : "0";
                    String newMAR = this.stats.isCurrentProcessAvailable() ? String.valueOf(this.stats.currentProcess.mar()) : "0";
                    
                    String newCurrentCycle = String.valueOf(this.stats.currentCycle);

                    this.completedProcessesField.setText(newCompletedProcessesField);
                    this.avgWaitField.setText(newAvgWaitField);
                    this.avgRespField.setText(newAvgRespField);
                    this.avgTurnField.setText(newAvgTurnField);
                    this.cpuUsageField.setText(newCpuUsageField);
                    this.throughputField.setText(newThroughputField);
                    this.fairnessField.setText(newFairnessField);
                    
                    this.currentProcessField.setText(newCurrentField);
                    this.ReadyList.setListData(newReadyList);
                    this.BlockedList.setListData(newIoList);
                    this.FinishedList.setListData(newfinishedList);
                    
                    this.currentProcessIDField.setText(newId);
                    this.currentProcessNameField.setText(newName);
                    this.currentProcessInstructionsField.setText(newInstructions);
                    this.currentProcessPriorityField.setText(newPriority);
                    this.currentProcessPCField.setText(newPC);
                    this.currentProcessMARField.setText(newMAR);
                    
                    this.cycleField.setText(newCurrentCycle);
                    
                    this.updateLogs();
                } catch (InterruptedException e) {
                     Thread.currentThread().interrupt();
                }
            }
        }, "External-Updater");
        
        updater.start();
    }

    public void forceUpdateFields() {
        this.sim.updateReadyQueue();
        
        String[] newReadyList = this.stats.getReadyQueueList();
        
        this.ReadyList.setListData(newReadyList);
    }
    
    public void updateLogs() {
        String[] newLogsList = this.stats.getLogsList();
        
        this.LogsList.setListData(newLogsList);
        
        // this.LogsList.ensureIndexIsVisible(newLogsList.length - 1);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> BlockedList;
    private javax.swing.JList<String> FinishedList;
    private javax.swing.JList<String> LogsList;
    private javax.swing.JList<String> ReadyList;
    private javax.swing.JTextField avgRespField;
    private javax.swing.JTextField avgTurnField;
    private javax.swing.JTextField avgWaitField;
    private javax.swing.JTextField completedProcessesField;
    private javax.swing.JMenu configButton;
    private javax.swing.JTextField cpuUsageField;
    private javax.swing.JMenu createButton;
    private javax.swing.JTextField currentProcessField;
    private javax.swing.JTextField currentProcessIDField;
    private javax.swing.JTextField currentProcessInstructionsField;
    private javax.swing.JTextField currentProcessMARField;
    private javax.swing.JTextField currentProcessNameField;
    private javax.swing.JTextField currentProcessPCField;
    private javax.swing.JTextField currentProcessPriorityField;
    private javax.swing.JTextField cycleField;
    private javax.swing.JTextField fairnessField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton pauseButton;
    private javax.swing.JComboBox<String> planPolicySelector;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField throughputField;
    // End of variables declaration//GEN-END:variables
}
